### ISSUE TITLE
Wiki links broken

### ISSUE THREAD

**Issue by pmarjora** [USCbiostats/software-dev#10]
@gvegayon 
I think the wiki links on the software dev page need to be updated to point to the new wiki

**Comment by gvegayon** [comment]
Not sure what links are now broken. I just changed the Home of the old wiki, pointing to the new one. Could you provide a couple of examples indicating where the broken links are?

**Comment by gvegayon** [comment]
No, you are looking at the old wiki. The new wiki is located here: https://github.com/USCbiostats/software-dev/blob/master/wiki#welcome-to-the-software-development-wiki, and the links within that page are all fixed.

If people try to go to the link you posted, it will take them to the "The old wiki has migrated" page, so yes, by design. Other than that, we can't do.

**Comment by pmarjora** [comment]
First shot shows the web address, second shows the links.
It looks to me like the changes you made to the ReadME.Rmd are not showing up in the ReadMe.md file (for me at least).

[Screen Capture1.pdf](https://github.com/USCbiostats/software-dev/files/7368098/Screen.Capture1.pdf)
[Screen Capture2.pdf](https://github.com/USCbiostats/software-dev/files/7368097/Screen.Capture2.pdf)

**Comment by gvegayon** [comment]
Thank you! Now I see the issue. Will update and let you know.

George G. Vega Yon, Ph.D.
(from mobile)
https://ggvy.cl
Pronouns: he/him/él

**Comment by gvegayon** [comment]
Solved in 20dbed0a86223da9ab204b3345b2a213a69397a6
